name: ðŸš€ AKS Workflow Execution

on:
  workflow_dispatch:

jobs:
  call-aks-template:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository (DevSecOps-scripts)
        uses: actions/checkout@v3
        with:
          repository: test-craizy/DevSecOps-scripts
          token: ${{ secrets.GH_PAT }}
          path: DevSecOps-scripts

      - name: Call Reusable Workflow
        uses: ./DevSecOps-scripts/.github/workflows/workflow-aks-template.yml
        with:
          componente: "backend-service"
